# Simple Custom Linux Distro Configuration
# Copy this file and edit it to create your own Linux distribution

[meta]
OS_NAME = "MyLinux"           # Change this to your distro name
OS_VERSION = "1.0"            # Your distro version

[general]
# Build settings - adjust based on your system
BUILDDIR = "/mnt/build_dir"   # Where to build (needs ~10GB space)
JHALFSDIR = "/mnt/build_dir/jhalfs"
LOGDIR = "./logs"
N_PARALLEL = 4                # Number of CPU cores to use
RUNMAKE = true                # Actually run the build
GETPKG = true                 # Download packages automatically
CUSTOM_TOOLS = true           # Include custom packages below
REBUILD_MAKEFILE = false
ALL_CORES = false

# Example: Add a text editor
[[packages]]
name = "nano"
version = "7.2"
url = "https://ftp.gnu.org/gnu/nano/nano-7.2.tar.xz"
build = [
  "./configure --prefix=/usr --sysconfdir=/etc",
  "make -j$(nproc)",
  "make install"
]

# Example: Add a network tool
[[packages]]
name = "wget"
version = "1.21.4"
url = "https://ftp.gnu.org/gnu/wget/wget-1.21.4.tar.gz"
build = [
  "./configure --prefix=/usr --sysconfdir=/etc",
  "make -j$(nproc)",
  "make install"
]

# Add more packages here...
# [[packages]]
# name = "your-package"
# version = "1.0"
# url = "https://example.com/your-package-1.0.tar.gz"
# build = [
#   "./configure --prefix=/usr",
#   "make -j$(nproc)",
#   "make install"
# ]
