# Converted from XML by xml_to_toml_converter.py
# Edit this TOML file instead of XML files

[package_manager]
enabled = true
type = "unknown"

[package_manager.commands]
install = [
  "Instructions",
  "./configure --prefix=/tools \\",
  "--disable-nls --without-dselect \\",
  "--without-start-stop-daemon \\",
  "--without-update-alternatives \\",
  "--without-install-info \\",
  "--without-zlib --with-bz2=static --without-selinux",
  "(cd lib  && make)",
  "(cd src && make)",
  "(cd dpkg-deb && make)",
  "(cd dpkg-split && make)",
  "cp src/dpkg src/dpkg-* /tools/bin",
  "cp dpkg-deb/dpkg-deb /tools/bin",
  "cp dpkg-split/dpkg-split /tools/bin",
  "mkdir -pv /tools/etc/dpkg/{,dpkg.cfg.d}",
  "cp debian/dpkg.cfg /tools/etc/dpkg",
  "cat >> /tools/etc/dpkg/dpkg.cfg << EOF",
  "# admindir on LFS system",
  "admindir /var/lib/dpkg",
  "EOF",
  "cat >> /tools/etc/dpkg/dpkg.cfg << EOF",
  "# disable fatal error on path checking",
  "force-bad-path",
  "EOF",
  "Instructions",
  "./configure --prefix=/tools \\",
  "--disable-nls --without-dselect \\",
  "--without-start-stop-daemon \\",
  "--without-update-alternatives \\",
  "--without-install-info \\",
  "--without-zlib --with-bz2=static --without-selinux",
  "(cd lib  && make)",
  "(cd src && make)",
  "(cd dpkg-deb && make)",
  "(cd dpkg-split && make)",
  "cp src/dpkg src/dpkg-* /tools/bin",
  "cp dpkg-deb/dpkg-deb /tools/bin",
  "cp dpkg-split/dpkg-split /tools/bin",
  "mkdir -pv /tools/etc/dpkg/{,dpkg.cfg.d}",
  "cp debian/dpkg.cfg /tools/etc/dpkg",
  "cat >> /tools/etc/dpkg/dpkg.cfg << EOF",
  "# admindir on LFS system",
  "admindir /var/lib/dpkg",
  "EOF",
  "cat >> /tools/etc/dpkg/dpkg.cfg << EOF",
  "# disable fatal error on path checking",
  "force-bad-path",
  "EOF",
  "mkdir -pv /var/{log,lib/dpkg/{info,updates}}",
  "mkdir -pv /var/lib/packages",
  "touch /var/lib/dpkg/{available,status}",
  "touch /var/log/dpkg.log",
  "./configure --prefix=/usr \\",
  "--without-dselect \\",
  "--without-start-stop-daemon \\",
  "--without-update-alternatives \\",
  "--without-install-info \\",
  "--without-selinux",
  "make",
  "mkdir -pv $PKG_DEST",
  "make DESTDIR=$PKG_DEST install",
  "mkdir -pv $PKG_DEST/etc/dpkg/{,dpkg.cfg.d}",
  "cp debian/dpkg.cfg $PKG_DEST/etc/dpkg",
  "cat >> $PKG_DEST/etc/dpkg/dpkg.cfg << EOF",
  "# admindir on LFS system",
  "admindir /var/lib/dpkg",
  "EOF",
  "cat >> $PKG_DEST/etc/dpkg/dpkg.cfg << EOF",
  "# disable fatal error on path checking",
  "force-bad-path",
  "EOF",
]

[[packages]]
url = "http://your/package-manager/url"
filename = "url"
name = "url"

[[packages]]
url = "somepatch-url"
filename = "somepatch-url"
name = "somepatch"

