# TOML Package Manager Configuration
# Replaces packageManager.xml files

[package_manager]
name = "porg"  # or "dpkg", "pacman", "none"
enabled = true
wrap_install = true  # Wrap install commands

[package_manager.config]
# Package manager specific configuration
install_root = "/usr"
database_dir = "/var/lib/porg"
log_dir = "/var/log/porg"

# Package manager commands (replaces XML templates)
[package_manager.commands]
# Command to install a package from source
install_command = """
#!/bin/bash
PKG_NAME="$1"
PKG_VERSION="$2"
BUILD_DIR="$3"

# Porg-style package management
porg -lp ${PKG_NAME}-${PKG_VERSION} -+ make install
"""

# Command to remove a package
remove_command = """
#!/bin/bash
PKG_NAME="$1"
PKG_VERSION="$2"

porg -r ${PKG_NAME}-${PKG_VERSION}
"""

# Command to list installed packages
list_command = """
#!/bin/bash
porg
"""

# Package download and verification
[packages.urls]
# Common package URLs (replaces parts of XML processing)
base_url = "http://ftp.gnu.org/gnu"
kernel_url = "https://cdn.kernel.org/pub/linux/kernel"
sourceforge_url = "https://downloads.sourceforge.net"

[packages.verification]
# Package verification settings
verify_checksums = true
verify_signatures = false
allow_http = true  # Allow HTTP downloads (not just HTTPS)

# LFS Base packages in TOML format (replaces XML book parsing)
[[lfs_packages]]
name = "binutils"
version = "2.43.1"
url = "https://ftp.gnu.org/gnu/binutils/binutils-2.43.1.tar.xz"
md5 = "sha256:13f74202a3c4c51118b797a39ea4200d3f6cfbe224da6d1d95bb938480132dfd"
chapter = 5
pass = 1

[[lfs_packages]]
name = "gcc"
version = "14.2.0"
url = "https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.xz"
md5 = "sha256:a7b39bc69cbf9e25826c5a60ab26477001f7c08d85cec04bc0e29cabed6f3cc9"
chapter = 5
pass = 1

[[lfs_packages]]
name = "linux"
version = "6.10.5"
url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.10.5.tar.xz"
md5 = "sha256:0b15d1d9cc89ea5b5e2a98dbde1ad71ac3be6d4ba375b7e6dcef6b2e8ae24cdd"
chapter = 5
component = "headers"

[[lfs_packages]]
name = "glibc"
version = "2.40"
url = "https://ftp.gnu.org/gnu/glibc/glibc-2.40.tar.xz"
md5 = "sha256:19a890175e9263d748f627993de6f4b1af9cd21e03f080e4bfb3a1fac10205a2"
chapter = 5

[[lfs_packages]]
name = "bash"
version = "5.2.21"
url = "https://ftp.gnu.org/gnu/bash/bash-5.2.21.tar.gz"
md5 = "sha256:c8e31bdc59b69aaffc5b36509905ba3e5cbb12747091978f582a06f7ca7f8677"
chapter = 6

[[lfs_packages]]
name = "coreutils"
version = "9.5"
url = "https://ftp.gnu.org/gnu/coreutils/coreutils-9.5.tar.xz"
md5 = "sha256:cd328edeac92f6a665de9f323c93b712af1858bc2e0d88f3f7100469470a1b8a"
chapter = 6

[[lfs_packages]]
name = "ncurses"
version = "6.5"
url = "https://ftp.gnu.org/gnu/ncurses/ncurses-6.5.tar.gz"
md5 = "sha256:136d91bc269a9a5785e5f9e980bc76ab57428f604ce3e5a5a90cebc767971cc6"
chapter = 6

# Build instructions per chapter (replaces XSLT logic)
[build_instructions.chapter5]
description = "Cross-compilation toolchain"
chroot = false
user = "lfs"
environment = ["LFS=/mnt/lfs", "LC_ALL=POSIX", "PATH=/usr/bin:/bin"]

[build_instructions.chapter6]
description = "Cross-compiling temporary tools"
chroot = false
user = "lfs"
environment = ["LFS=/mnt/lfs", "LC_ALL=POSIX", "PATH=/usr/bin:/bin:/tools/bin"]

[build_instructions.chapter7]
description = "Chroot temporary tools"
chroot = true
user = "root"
environment = ["PATH=/usr/bin:/bin:/tools/bin"]

[build_instructions.chapter8]
description = "Final system packages"
chroot = true
user = "root"
environment = ["PATH=/usr/bin:/bin"]
package_management = true
